name: CD Testing
run-name: "[Manual] @${{ github.actor }} testing variables"

on:
  release:
    types: 
      - published
      
jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print variable
        run: echo ${{ github.event.release.tag_name }}
